# Generated by Django 5.2.4 on 2025-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('group', models.CharField(max_length=1)),
                ('ratings_data', models.JSONField()),
                ('perceived_accuracy', models.IntegerField(blank=True, null=True)),
                ('trust', models.IntegerField(blank=True, null=True)),
                ('qualitative_feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
